name: starphone-backend
services:
  api:
    image: starphone-api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env"
    ports:
      - "8000:8000"
    depends_on:
      - db
    working_dir: /app
    restart: unless-stopped
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    shm_size: 128mb
    volumes:
      - starphone_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=starphone
      - POSTGRES_USER=starphone
      - POSTGRES_PASSWORD=starphone123

volumes:
  starphone_pg_data: